# services:
#   - type: web
#     name: utar-chatbot
#     env: python
#     plan: standard
#     buildCommand: "pip install -r requirements.txt"
#     startCommand: "gunicorn app:app --timeout 180 --workers 1 --threads 2 --preload"
services:
  # Backend (Flask)
  - type: web
    name: utar-chatbot-backend
    env: python
    region: singapore
    plan: standard
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 180 --workers 1 --threads 2 --preload"
    disk:
      name: vectordb-disk
      mountPath: /var/data
      sizeGB: 10

  # Frontend (React in chatbot-ui/)
  - type: web
    name: utar-chatbot-frontend
    env: static
    region: singapore
    buildCommand: "npm install && npm run build"
    staticPublishPath: chatbot-ui/build   # if Vite; use chatbot-ui/build if CRA