services:
  # Backend (Flask)
  - type: web
    name: utar-chatbot-backend
    env: python
    region: singapore
    plan: standard
    buildCommand: "pip install -r requirements.txt"
    # Increased timeout for first-time database loading per department
    # Reduced workers to 1 but increased threads for better memory management
    startCommand: "gunicorn app:app --timeout 600 --workers 1 --threads 2 --max-requests 1000 --max-requests-jitter 100"